spring:
  application:
    name: otelcommander
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:example@localhost:27017/commander?authSource=admin}
      database: commander
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/x-protobuf
    min-response-size: 1B