spring:
  application:
    name: otelcommander
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:example@localhost:27017,localhost:27018,localhost:27019/commander?replicaSet=rs0&authSource=admin}
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/x-protobuf
    min-response-size: 1B