spring:
  application:
    name: opampcommander
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:example@localhost:27017/commander?authSource=admin}
      database: commander
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/x-protobuf
    min-response-size: 1B

springdoc:
  swagger-ui:
    path: /docs
  group-configs:
    - group: "admin"
      paths: "/v1/admin/**"
      packagesToScan: "dev.minuk.opampcommander.adapter.primary.http.api.v1.admin"
    - group: "opamp"
      paths: "/v1/opamp/**"
      packagesToScan: "dev.minuk.opampcommander.adapter.primary.http.api.v1.opamp"