services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.110.0
    restart: always
    ports:
        - 4317:4317
        - 55678:55678
    volumes:
        - ${PWD}/data/config.yaml:/etc/config.yaml
    command: ["--config", "/etc/config.yaml"]